const DAY = 24 * 60 * 60 * 1000

function iso(daysFromNow: number, hour = 10) {
  const date = new Date(Date.now() + daysFromNow * DAY)
  date.setHours(hour, 0, 0, 0)
  return date.toISOString()
}

function ymd(daysFromNow: number) {
  return iso(daysFromNow).slice(0, 10)
}

export const DEMO_OWNER = {
  id: 'demo-owner-sales',
  name: 'デモ担当',
  email: 'demo-sales@example.com',
}

const demoCompanies = [
  { id: 'demo-company-td', name: '株式会社T&Dホールディングス', rank: 'A' },
  { id: 'demo-company-ntt', name: '株式会社NTT', rank: 'A' },
  { id: 'demo-company-eneos', name: '株式会社ENEOSホールディングス', rank: 'B' },
  { id: 'demo-company-sms', name: '株式会社エス・エム・エス', rank: 'B' },
  { id: 'demo-company-m3', name: '株式会社エムスリー', rank: 'C' },
] as const

const demoContacts = [
  { id: 'demo-contact-td-1', name: '佐藤 亮', email: 'demo.sato@example.com', phone: '03-6200-1184' },
  { id: 'demo-contact-ntt-1', name: '高橋 美咲', email: 'demo.takahashi@example.com', phone: '03-6200-2193' },
  { id: 'demo-contact-eneos-1', name: '鈴木 健太', email: 'demo.suzuki@example.com', phone: '03-6200-3328' },
  { id: 'demo-contact-sms-1', name: '伊藤 直子', email: 'demo.ito@example.com', phone: '03-6200-4471' },
  { id: 'demo-contact-m3-1', name: '田中 拓也', email: 'demo.tanaka@example.com', phone: '03-6200-5820' },
] as const

export function getDemoDealsForApi() {
  return [
    {
      id: 'demo-deal-td-division-phone',
      name: '部署直通番号DB 活用提案',
      stage: 'PROPOSAL',
      amount: 3600000,
      probability: 68,
      expectedCloseAt: iso(21, 18),
      createdAt: iso(-18),
      updatedAt: iso(-1, 16),
      nextActionUs: '営業部門と人事部門の利用部門を整理し、決裁者向けの費用対効果資料を送付する',
      desiredService: '部署番号・求人インテントを使ったABM運用を検討中',
      timeline: '今月中に比較表を確認し、来月PoC判断',
      company: demoCompanies[0],
      contact: demoContacts[0],
      owner: DEMO_OWNER,
      _count: { emailMessages: 8, meetingEvents: 2 },
    },
    {
      id: 'demo-deal-ntt-intent',
      name: '採用インテント検知 導入相談',
      stage: 'FIRST_MEETING',
      amount: 2400000,
      probability: 42,
      expectedCloseAt: iso(35, 17),
      createdAt: iso(-12),
      updatedAt: iso(-2, 11),
      nextActionUs: '対象部署の抽出条件をヒアリングし、HOT企業リストのサンプルを作成する',
      desiredService: '採用予算の見える化と重点アプローチ先の抽出',
      timeline: '四半期内にISチームでテスト利用',
      company: demoCompanies[1],
      contact: demoContacts[1],
      owner: DEMO_OWNER,
      _count: { emailMessages: 5, meetingEvents: 1 },
    },
    {
      id: 'demo-deal-eneos-poc',
      name: 'エンタープライズ営業リスト PoC',
      stage: 'NEGOTIATION',
      amount: 5200000,
      probability: 78,
      expectedCloseAt: iso(14, 15),
      createdAt: iso(-29),
      updatedAt: iso(0, 9),
      nextActionUs: 'PoC結果レポートを共有し、契約開始月と利用席数を確定する',
      desiredService: '大手企業向けABMと部署別アプローチを本格導入したい',
      timeline: 'PoC完了後、翌月から本契約開始を想定',
      company: demoCompanies[2],
      contact: demoContacts[2],
      owner: DEMO_OWNER,
      _count: { emailMessages: 13, meetingEvents: 3 },
    },
    {
      id: 'demo-deal-sms-is',
      name: 'ISリスト自動生成 トライアル',
      stage: 'QUALIFIED',
      amount: 1680000,
      probability: 34,
      expectedCloseAt: iso(45, 12),
      createdAt: iso(-8),
      updatedAt: iso(-1, 10),
      nextActionUs: '医療・介護業界に絞ったアプローチリストを作成し、反応率を確認する',
      desiredService: '業界別に精度の高い新規開拓リストが必要',
      timeline: '2週間以内に初回リストを確認',
      company: demoCompanies[3],
      contact: demoContacts[3],
      owner: DEMO_OWNER,
      _count: { emailMessages: 3, meetingEvents: 0 },
    },
    {
      id: 'demo-deal-m3-multi',
      name: '営業・マーケ連携ダッシュボード',
      stage: 'SOLUTION_FIT',
      amount: 3000000,
      probability: 55,
      expectedCloseAt: iso(28, 16),
      createdAt: iso(-22),
      updatedAt: iso(-4, 14),
      nextActionUs: '配信クリックと商談化の関係を見せるデモレポートを準備する',
      desiredService: '配信から商談までを一気通貫で可視化したい',
      timeline: '今月中にマーケ責任者へ共有',
      company: demoCompanies[4],
      contact: demoContacts[4],
      owner: DEMO_OWNER,
      _count: { emailMessages: 9, meetingEvents: 2 },
    },
  ]
}

export function getDemoTasksForApi(scope?: string | null) {
  const tasks = [
    {
      id: 'demo-task-1',
      type: 'call',
      company: '株式会社ENEOSホールディングス',
      person: '鈴木 健太',
      rank: 'A',
      urgent: true,
      owner: DEMO_OWNER.id,
      ownerName: DEMO_OWNER.name,
      category: 'deal',
      linkTo: '/deals/demo-deal-eneos-poc',
      title: 'PoC結果レポートの確認コール',
      memo: '利用部門別の反応率と部署番号の有効性を10分で確認する',
      dueAt: ymd(0),
      remindAt: '',
      completed: false,
    },
    {
      id: 'demo-task-2',
      type: 'email',
      company: '株式会社T&Dホールディングス',
      person: '佐藤 亮',
      rank: 'A',
      urgent: true,
      owner: DEMO_OWNER.id,
      ownerName: DEMO_OWNER.name,
      category: 'deal',
      linkTo: '/deals/demo-deal-td-division-phone',
      title: '費用対効果資料を送付',
      memo: '採用予算と部署番号のサンプル付きで送る',
      dueAt: ymd(1),
      remindAt: '',
      completed: false,
    },
    {
      id: 'demo-task-3',
      type: 'meeting',
      company: '株式会社NTT',
      person: '高橋 美咲',
      rank: 'B',
      urgent: false,
      owner: DEMO_OWNER.id,
      ownerName: DEMO_OWNER.name,
      category: 'deal',
      linkTo: '/deals/demo-deal-ntt-intent',
      title: 'インテント抽出条件のヒアリング',
      memo: '部署、求人職種、拠点条件を確認する',
      dueAt: ymd(3),
      remindAt: '',
      completed: false,
    },
    {
      id: 'demo-task-4',
      type: 'followup',
      company: '株式会社エムスリー',
      person: '田中 拓也',
      rank: 'C',
      urgent: false,
      owner: DEMO_OWNER.id,
      ownerName: DEMO_OWNER.name,
      category: 'deal',
      linkTo: '/deals/demo-deal-m3-multi',
      title: 'マーケ責任者向けレポート作成',
      memo: '配信クリック、返信、商談化の流れを1枚で整理する',
      dueAt: ymd(5),
      remindAt: '',
      completed: false,
    },
  ]
  if (scope === 'today') return tasks.filter((task) => task.dueAt === ymd(0))
  if (scope === 'overdue') return []
  return tasks
}

export const DEMO_CONTACTS = [
  {
    id: 'demo-contact-td-1',
    name: '佐藤 亮',
    title: '営業企画 部長',
    department: '営業企画部',
    personRole: '決裁者',
    company: '株式会社T&Dホールディングス',
    companyId: 'demo-company-td',
    rank: 'A',
    status: '接続済み',
    contactStatus: '商談中',
    leadSource: { type: 'cold_mail', detail: 'HOT企業向け初回メール' },
    callAttempts: 3,
    emailsSent: 5,
    lastCallAt: ymd(-1),
    nextActionAt: ymd(1),
    nextAction: 'メールアプローチ',
    owner: DEMO_OWNER.name,
  },
  {
    id: 'demo-contact-ntt-1',
    name: '高橋 美咲',
    title: '人事企画 マネージャー',
    department: '人事企画部',
    personRole: '推進者',
    company: '株式会社NTT',
    companyId: 'demo-company-ntt',
    rank: 'A',
    status: 'アポ獲得',
    contactStatus: '商談中',
    leadSource: { type: 'event', detail: '採用DXウェビナー参加' },
    callAttempts: 2,
    emailsSent: 4,
    lastCallAt: ymd(-2),
    nextActionAt: ymd(3),
    nextAction: 'コール',
    owner: DEMO_OWNER.name,
  },
  {
    id: 'demo-contact-eneos-1',
    name: '鈴木 健太',
    title: 'DX推進 課長',
    department: 'DX推進部',
    personRole: '推進者',
    company: '株式会社ENEOSホールディングス',
    companyId: 'demo-company-eneos',
    rank: 'B',
    status: '接続済み',
    contactStatus: '商談中',
    leadSource: { type: 'referral', detail: '既存顧客からの紹介' },
    callAttempts: 4,
    emailsSent: 7,
    lastCallAt: ymd(0),
    nextActionAt: ymd(0),
    nextAction: '連絡待ち',
    owner: DEMO_OWNER.name,
  },
  {
    id: 'demo-contact-sms-1',
    name: '伊藤 直子',
    title: '事業開発 リーダー',
    department: '事業開発部',
    personRole: '一般',
    company: '株式会社エス・エム・エス',
    companyId: 'demo-company-sms',
    rank: 'B',
    status: '不在',
    contactStatus: 'リード',
    leadSource: { type: 'organic_search', detail: '部署番号DB 検索流入' },
    callAttempts: 2,
    emailsSent: 2,
    lastCallAt: ymd(-4),
    nextActionAt: ymd(2),
    nextAction: 'コール',
    owner: DEMO_OWNER.name,
  },
] as const

export const DEMO_LISTS = [
  {
    id: 'demo-list-hot-enterprise',
    kind: 'is',
    name: 'HOT企業_今週架電',
    description: '求人インテントHOTかつ部署番号ありの大手企業',
    ownerName: DEMO_OWNER.name,
    contactCount: 84,
    completedCount: 52,
    appointmentCount: 12,
    color: '#0071E3',
    createdAt: iso(-12),
    updatedAt: iso(-1),
  },
  {
    id: 'demo-list-no-reply',
    kind: 'is',
    name: '資料クリック済み_未返信',
    description: '配信資料を開封したが返信がない企業を再フォロー',
    ownerName: DEMO_OWNER.name,
    contactCount: 46,
    completedCount: 31,
    appointmentCount: 7,
    color: '#34C759',
    createdAt: iso(-9),
    updatedAt: iso(-2),
  },
  {
    id: 'demo-list-hr-budget',
    kind: 'is',
    name: '採用予算あり_人事部門',
    description: '採用予算推定あり、人事・採用部署への初回接触リスト',
    ownerName: DEMO_OWNER.name,
    contactCount: 128,
    completedCount: 76,
    appointmentCount: 18,
    color: '#FF9F0A',
    createdAt: iso(-18),
    updatedAt: iso(-3),
  },
] as const

export function getDemoTicketsForApi() {
  return [
    {
      id: 'demo-ticket-1',
      ticketNumber: 101,
      subject: '部署番号の更新頻度を確認したい',
      status: 'OPEN',
      createdAt: iso(-1, 11),
      updatedAt: iso(0, 9),
      resolvedAt: null,
      estimatedCompletionAt: iso(1, 18),
      deal: { id: 'demo-deal-td-division-phone', name: '部署直通番号DB 活用提案' },
      company: { id: 'demo-company-td', name: '株式会社T&Dホールディングス' },
      assignee: { id: DEMO_OWNER.id, name: DEMO_OWNER.name },
    },
    {
      id: 'demo-ticket-2',
      ticketNumber: 102,
      subject: 'HOT判定の条件を営業部門向けに説明したい',
      status: 'PENDING',
      createdAt: iso(-3, 15),
      updatedAt: iso(-1, 14),
      resolvedAt: null,
      estimatedCompletionAt: iso(2, 17),
      deal: { id: 'demo-deal-ntt-intent', name: '採用インテント検知 導入相談' },
      company: { id: 'demo-company-ntt', name: '株式会社NTT' },
      assignee: { id: DEMO_OWNER.id, name: DEMO_OWNER.name },
    },
    {
      id: 'demo-ticket-3',
      ticketNumber: 103,
      subject: 'CSV出力時に部署名を含めたい',
      status: 'SOLVED',
      createdAt: iso(-7, 10),
      updatedAt: iso(-2, 16),
      resolvedAt: iso(-2, 16),
      estimatedCompletionAt: iso(-2, 18),
      deal: { id: 'demo-deal-eneos-poc', name: 'エンタープライズ営業リスト PoC' },
      company: { id: 'demo-company-eneos', name: '株式会社ENEOSホールディングス' },
      assignee: { id: DEMO_OWNER.id, name: DEMO_OWNER.name },
    },
  ]
}

export function getDemoTicketDetail(id: string) {
  const ticket = getDemoTicketsForApi().find((item) => item.id === id)
  if (!ticket) return null
  return {
    ...ticket,
    orgId: 'demo-org',
    description:
      ticket.id === 'demo-ticket-1'
        ? '営業リストを更新する際、部署直通番号がどのくらいの頻度で更新されるかを顧客向け資料に記載したい。'
        : ticket.id === 'demo-ticket-2'
          ? '求人インテントのHOT/MID/LOWの判定基準を、営業部門にも説明できる粒度で整理したい。'
          : '商談後にCSVで社内共有するため、企業名・部署名・担当者名・採用予算を同時に出力したい。',
    cause: 'デモ環境で想定される顧客問い合わせのサンプルです。',
    resolution: ticket.status === 'SOLVED' ? 'CSV項目に部署名を追加する運用で対応済み。' : null,
    memo: 'このデータはデモ表示用のダミーデータです。',
    dealId: ticket.deal?.id ?? null,
    companyId: ticket.company?.id ?? null,
    contactId: null,
    assigneeUserId: DEMO_OWNER.id,
    contact: null,
    closedAt: null,
  }
}
